package com.email.webserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://localhost:90/Ebay")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloService {

	/**
     * 
     */
	@WebMethod
	public void sayHello();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getInfo(
			@WebParam(name = "arg0", partName = "arg0") String arg0);

}
